# Generated by Django 3.1.3 on 2021-03-26 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The name of the menu, used as the url.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('greeting_text', models.CharField(blank=True, help_text='The text to say when entering this menu.', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(help_text='Twilio voice (ex: man, woman).', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('menu_digit', models.IntegerField(help_text='The key press to access during twilio call.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('menu_text', models.CharField(blank=True, help_text='The text to say in the twilio menu. Will be prefixed with "Press N ". If left blank, it will be a hidden menu.', max_length=200, null=True)),
                ('action_text', models.CharField(blank=True, help_text='The text to say when selected by twilio menu. If action phone is specified and this is blank, will use "Transferring, please wait.".', max_length=400, null=True)),
                ('action_phone', models.CharField(blank=True, help_text='If specified, will transfer to this number when selected by twilio menu.', max_length=15, null=True)),
                ('action_url', models.CharField(blank=True, help_text='If specified, will send twilio to this url.', max_length=400, null=True)),
                ('action_submenu', models.ForeignKey(blank=True, help_text='If specified, will send twilio to this submenu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenu_item_set', to='twilio_call_center.menu')),
                ('menu', models.ForeignKey(blank=True, help_text='The menu this item is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item_set', to='twilio_call_center.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='voice',
            field=models.ForeignKey(blank=True, help_text='Twilio voice, if unset default to "woman".', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_call_center.voice'),
        ),
    ]
