# Generated by Django 4.0.7 on 2022-12-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_call_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_list', models.TextField(blank=True, null=True)),
                ('available_start', models.TimeField(blank=True, null=True)),
                ('available_stop', models.TimeField(blank=True, null=True)),
                ('always_send_voicemail', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='action_text',
            field=models.CharField(blank=True, help_text='The text to say when selected by twilio menu. If action mailbox phone is specified and this is blank, will use "Transferring, please wait.".', max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='Voicemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=40, unique=True)),
                ('call_sid', models.CharField(max_length=40, unique=True)),
                ('from_phone', models.CharField(max_length=20)),
                ('to_phone', models.CharField(max_length=20)),
                ('transcription', models.TextField(blank=True, help_text='A transcription of the recorded message', null=True)),
                ('url', models.CharField(help_text='The url to the recording', max_length=256)),
                ('status', models.CharField(max_length=32)),
                ('last_activity', models.DateTimeField()),
                ('mailbox', models.ForeignKey(blank=True, help_text='The specific mailbox the message was sent to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_call_center.mailboxnumber')),
                ('menu_item', models.ForeignKey(blank=True, help_text='The specific menu item used to send this message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_call_center.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='action_mailbox',
            field=models.ForeignKey(blank=True, help_text='If specified, will transfer to this number or mailbox', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_call_center.mailboxnumber'),
        ),
    ]
