# Generated by Django 4.0.7 on 2022-12-15 16:42

from django.db import migrations, models
import twilio_call_center.models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_call_center', '0002_add_voicemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxnumber',
            name='available_start',
            field=models.TimeField(blank=True, help_text='If time is before this, record a voicemail. If this is blank, always send to the phone number', null=True),
        ),
        migrations.AlterField(
            model_name='mailboxnumber',
            name='available_stop',
            field=models.TimeField(blank=True, help_text='If time is after this, record a voicemail. If this is blank, always send to the phone number', null=True),
        ),
        migrations.AlterField(
            model_name='mailboxnumber',
            name='email_list',
            field=models.TextField(blank=True, help_text='A comma separated list of emails which receive voicemail notifications.', null=True, validators=[twilio_call_center.models.validate_email_list]),
        ),
        migrations.AlterField(
            model_name='mailboxnumber',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number to connect to. If left blank, always send to voicemail.', max_length=20, null=True),
        ),
    ]
