# Generated by Django 4.0.7 on 2022-12-19 22:17

from django.db import migrations, models
import twilio_call_center.models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_call_center', '0003_add_mailboxnumber_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='pin_digits_list',
            field=models.CharField(blank=True, help_text='If specified, caller will have to enter one of the pins in this comma separated list before any actions are taken.', max_length=200, null=True, validators=[twilio_call_center.models.validate_pin_digits_list]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pin_text',
            field=models.CharField(blank=True, help_text='If specified, say this when asking for a pin. Does nothing when Pin digits list is not specified.', max_length=200, null=True),
        ),
    ]
