# Generated by Django 4.0.7 on 2022-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_call_center', '0004_add_menu_item_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='action_function',
            field=models.CharField(blank=True, help_text='If specified, will call the given function and say the result.', max_length=100, null=True),
        ),
    ]
