# Generated by Django 4.0.7 on 2023-01-18 04:05

from django.db import migrations, models
import django.db.models.deletion
import twilio_call_center.models
import twilio_call_center.validators


class Migration(migrations.Migration):
    # Altering many of the text based fields to remove null=True
    # sometimes causes errors migrating with postgresql. For example:
    #       django.db.utils.DatabaseError: cannot ALTER TABLE
    #       "twilio_call_center_menuitem" because it has pending trigger events
    # Use non-atomic transactions to get around this
    atomic = False

    dependencies = [
        ('twilio_call_center', '0005_add_action_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=40, unique=True)),
                ('from_phone', twilio_call_center.models.PhoneField(max_length=20)),
                ('to_phone', twilio_call_center.models.PhoneField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('last_activity', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TwilioNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('phone', twilio_call_center.models.PhoneField(max_length=20, unique=True)),
                ('forward_phone_list', models.TextField(blank=True, help_text='A comma separated list of phone numbers which receive sms forward notifications.', validators=[twilio_call_center.validators.validate_phone_list])),
                ('forward_email_list', models.TextField(blank=True, help_text='A comma separated list of emails which receive sms forward notifications.', validators=[twilio_call_center.validators.validate_email_list])),
            ],
        ),
        migrations.AddField(
            model_name='mailboxnumber',
            name='phone_list',
            field=models.TextField(blank=True, help_text='A comma separated list of phone numbers which receive voicemail notifications via sms.', validators=[twilio_call_center.validators.validate_phone_list]),
        ),
        migrations.AlterField(
            model_name='mailboxnumber',
            name='email_list',
            field=models.TextField(blank=True, default='', help_text='A comma separated list of emails which receive voicemail notifications.', validators=[twilio_call_center.validators.validate_email_list]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailboxnumber',
            name='phone',
            field=twilio_call_center.models.PhoneField(blank=True, default='', help_text='Phone number to connect to. If left blank, always send to voicemail.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='greeting_text',
            field=models.CharField(blank=True, default='', help_text='The text to say when entering this menu.', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='action_function',
            field=models.CharField(blank=True, default='', help_text='If specified, will call the given function and say the result.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='action_text',
            field=models.CharField(blank=True, default='', help_text='The text to say when selected by twilio menu. If action mailbox phone is specified and this is blank, will use "Transferring, please wait.".', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='action_url',
            field=models.CharField(blank=True, default='', help_text='If specified, will send twilio to this url.', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_text',
            field=models.CharField(blank=True, default='', help_text='The text to say in the twilio menu. Will be prefixed with "Press N ". If left blank, it will be a hidden menu.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='pin_digits_list',
            field=models.CharField(blank=True, default='', help_text='If specified, caller will have to enter one of the pins in this comma separated list before any actions are taken.', max_length=200, validators=[twilio_call_center.validators.validate_pin_digits_list]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='pin_text',
            field=models.CharField(blank=True, default='', help_text='If specified, say this when asking for a pin. Does nothing when Pin digits list is not specified.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='from_phone',
            field=twilio_call_center.models.PhoneField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='to_phone',
            field=twilio_call_center.models.PhoneField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='transcription',
            field=models.TextField(blank=True, default='', help_text='A transcription of the recorded message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicemail',
            name='transcription_status',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailboxnumber',
            name='notification_phone',
            field=models.ForeignKey(blank=True, help_text='Use this phone number to send the sms notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_call_center.twilionumber'),
        ),
    ]
